---
title: "Code"
author: "Tim Wen"
date: "2026-02-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages and data

```{r}
library(dplyr)
library(stargazer)
library(sf)
library(MASS)
library(ggplot2)
library(patchwork)
library(knitr)
library(DAAG)

data=read.csv("RegressionData.csv")
```

## 1ai Use Stargazer to quickly calculate the summary statistics

```{r}
stargazer(data,
          type = "text",
          covariate.labels = c(
            "Polygon ID",
            "Area Key",
            "Median House Value",
            "Percentage of Bachelor's Degree or More",
            "Median Household Income (USD)",
            "Percentage of Vacant Housing Units",
            "Percentage of Singel Detached Houses",
            "No. Households Below Poverty Line"
          ),
          title = "Descriptive Statistics")
```
## 1a ii write a loop (cuz i am lazy first and then realize it actually took more time...) for creating his for variables and log variables
```{r}
#as the min value for PCTBACHMOR, PCTVACANT,PCTSINGLES, and NBELPOV100 is zero, we are going to use log(1+VAR) for them
#create log variable
data=data%>%
   mutate(
     LNMEDHVAL=log(MEDHVAL),
     LNPCBACHMORE=log(PCTBACHMOR+1),
     LNNBELPOV100=log(NBELPOV100+1),
     LNPCTVACANT=log(PCTVACANT+1),
     LNPCTSINGLES=log(PCTSINGLES+1)
   )

#set variable for a loop to create histogram
variable=c("MEDHVAL","PCTBACHMOR","NBELPOV100","PCTVACANT","PCTSINGLES")
#label for the histogram
labels <- c(
  MEDHVAL     = "Median House Value",
  PCTBACHMOR  = "Percentage of Residents with At Least Bachelor's Degree",
  NBELPOV100  = "Number of Households Below Poverty Line",
  PCTVACANT   = "Percentage Vacant Housing Units",
  PCTSINGLES  = "Percentage Detached Single Family Houses"
)
#loop for draw histogram across different variable
for (v in variable) {
  hist(data[[v]], main = NULL, xlab = labels[v])
}
```

```{r}
# same for log variable
lnvariable=c("LNMEDHVAL","LNPCBACHMORE","LNNBELPOV100","LNPCTVACANT","LNPCTSINGLES")
#label for the histogram
loglabels <- c(
  LNMEDHVAL     = "Log Median House Value",
  LNPCBACHMORE  = "Log Percentage of Residents with At Least Bachelor's Degree",
  LNNBELPOV100  = "Log Number of Households Below Poverty Line",
  LNPCTVACANT   = "Log Percentage Vacant Housing Units",
  LNPCTSINGLES  = "Log Percentage Detached Single Family Houses"
)
# loop for hist log variable
for (v in lnvariable) {
 hist(data[[v]], main = NULL, xlab = loglabels[v])
}
```

##1b another loop (lazy again) for the plot
```{r}
#define loop for final variable plot
finalvariable=c("LNNBELPOV100","PCTBACHMOR","PCTVACANT","PCTSINGLES")

finallabel <- c(
  MEDHVAL     = "Median House Value",
  PCTBACHMOR  = "Percentage of Residents with At Least Bachelor's Degree",
  LNNBELPOV100  = "Log Number of Households Below Poverty Line",
  PCTVACANT   = "Percentage Vacant Housing Units",
  PCTSINGLES  = "Percentage Detached Single Family Houses")
  
#set the plot and dimension
par(mfrow=c(2,2))
#loop for plotting all variables
for (v in finalvariable) {
  plot(data[[v]],data$LNMEDHVAL,ylab = "Log Median House Value",xlab = finallabel[v])
}
par(mfrow=c(1,1))
```

##1c another loop for correlation...
```{r}
library(dplyr)
#filter data for correlation calculation
cor_data=data%>% 
  dplyr::select("LNNBELPOV100","PCTBACHMOR","PCTVACANT","PCTSINGLES")
#calculate the correlation matrix
cor(cor_data)

```

##1d draw the maps
```{r}
#load the shapefile
data_sf=st_read("shapefile/RegressionData.shp")
#assign a crs
data_sf=st_set_crs(data_sf,2272)
#create ln variable for shapefile
data_sf=data_sf%>%
  mutate( LNMEDHVAL=log(MEDHVAL),
          LNPCBACHMORE=log(PCTBACHMOR+1),
          LNNBELPOV100=log(NBelPov100+1),
          LNPCTVACANT=log(PCTVACANT+1),
          LNPCTSINGLES=log(PCTSINGLES+1))
#map the median home value
ggplot(data_sf,aes(fill=LNMEDHVAL))+
  geom_sf(color = "black", linewidth = 0.2) + 
  scale_fill_continuous(low = "lightblue", high = "darkblue",name="Log Median\nHouse Value") +
  theme_void()

#map the rest variables
g1=ggplot(data_sf,aes(fill=LNNBELPOV100))+
  geom_sf(color = "black", linewidth = 0.2) + 
  scale_fill_continuous(low = "lightblue", high = "darkblue",name="Log Number of\nHouseholds Living in Poverty") +
  theme_void()

g2=ggplot(data_sf,aes(fill=PCTBACHMOR))+
  geom_sf(color = "black", linewidth = 0.2) + 
  scale_fill_continuous(low = "lightgreen", high = "red", name="Percentage of Residents\nwith At Least Bachelor's Degree") +
  theme_void()

g3=ggplot(data_sf,aes(fill=PCTVACANT))+
  geom_sf(color = "black", linewidth = 0.2) + 
  scale_fill_continuous(low = "lightblue", high = "red", name="Percentage of\nVacant Housing Units") +
  theme_void()

g4=ggplot(data_sf,aes(fill=PCTSINGLES))+
  geom_sf(color = "black", linewidth = 0.2) + 
  scale_fill_continuous(low = "yellow", high = "purple", name="Percentage of Detached\nSingle Family House") +
  theme_void()

(g1 + g2) / (g3 + g4)

```

##2a run the regression
```{r}
r1=lm(LNMEDHVAL~PCTVACANT+LNNBELPOV100+PCTBACHMOR+PCTSINGLES,data=data)
```

##2b result output
```{r}
#summary of the regression output
summary(r1)
#more professional: use stargezer for the output
stargazer(r1,
          type = "text",
          title = "OLS Regression Results: Determinants of Median House Value",
          dep.var.labels = "Log Median House Value",
          covariate.labels = c(
            "Percentage of Vacant Houses",
            "Log Number of Households Below Poverty Line",
            "Percentage of Bachelor's Degree or More",
            "Percentage of Detached Single Family House",
            "Constant"
          ),
          notes = "Standard errors in parentheses",
          star.cutoffs = c(0.05, 0.01, 0.001))
#anova
anova(r1)
```
##2c 
```{r}
#calculate fitted value, residuals and standardized residuals
data$fittedvalue=fitted(r1)
data$residual=residuals(r1)
data$stdresidual=rstandard(r1)
```

##2d
```{r}
#plot fitted value vs standardized residuals
plot(data$fittedvalue,data$stdresidual,xlab = "Fitted Value", ylab = "Standardized Residuals")
```

##3
```{r}
#calculate AIC
stepmodel=step(r1)
stepmodel$anova
```

##4
```{r}
#K-Fold cross validation
fullmodel=CVlm(
  data=data,
  form.lm = formula(LNMEDHVAL~PCTVACANT+LNNBELPOV100+PCTBACHMOR+PCTSINGLES),
  m=5)
```
```{r}
partmodel=CVlm(
  data=data,
  form.lm = formula(LNMEDHVAL~PCTVACANT+MEDHHINC),
  m=5)
```

##5
```{r}
#final residual map
#merge the residual with the spatial data
data_sf_map=data%>%
  dplyr::select("POLY_ID","stdresidual")%>%
  left_join(data_sf,by="POLY_ID")%>%
  st_as_sf() 

ggplot(data_sf_map,aes(fill=stdresidual))+
  geom_sf(color = "black", linewidth = 0.2) + 
  scale_fill_continuous(low = "lightgreen", high = "red", name="Standardized Residuals") +
  theme_void()

#histogram of the standard residuals
hist(data$stdresidual,xlab = "Standardized Residuals")

```

