library(aod)
library(ggplot2)
library(rms)
library(gmodels)
library(nnet)
library(DAAG)
library(ROCR)
library(xtable)

mydata <- read.csv("Logistic Regression Data.csv")
DRINKING_D.tab <- table(mydata$DRINKING_D)
prop.table(DRINKING_D.tab)
CrossTable(mydata$DRINKING_D,mydata$FATAL_OR_M, prop.c=TRUE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)
CrossTable(mydata$DRINKING_D,mydata$OVERTURNED, prop.c=TRUE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)
CrossTable(mydata$DRINKING_D,mydata$CELL_PHONE, prop.c=TRUE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)
CrossTable(mydata$DRINKING_D,mydata$SPEEDING, prop.c=TRUE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)
CrossTable(mydata$DRINKING_D,mydata$AGGRESSIVE, prop.c=TRUE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)
CrossTable(mydata$DRINKING_D,mydata$DRIVER1617, prop.c=TRUE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)
CrossTable(mydata$DRINKING_D,mydata$DRIVER65PLUS, prop.c=TRUE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)

tapply(mydata$PCTBACHMOR,
       mydata$DRINKING_D, mean)
tapply(mydata$PCTBACHMOR, mydata$DRINKING_D, sd)
t.test(mydata$PCTBACHMOR~mydata$DRINKING_D)
t.test(mydata$MEDHHINC~mydata$DRINKING_D)
